import datetime

data = {
    "bedrooms": 1,
    "displayAddress": "Fairlight Road, Tooting, SW17",
    "feesApply": True,
    "firstVisibleDate": datetime.datetime(2019, 4, 26, 19, 9, 54),
    "floorplanImages": ("https://media.rightmove.co.uk/dir/112k/600x600.png",),
    "id": "RM-81242870",
    "keyFeatures": ("Superb one bedroom flat",),
    "lettingInformation": {"Furnishing": "Unfurnished"},
    "location": {"latitude": 52.0, "longitude": -1.0},
    "price": {"amount": 1300, "currencyCode": "GBP", "frequency": "monthly"},
    "propertyImages": ("https://media.rightmove.co.uk/dir/112k/656x437.jpg",),
    "propertySubType": "Flat",
    "propertyTypeFullDescription": "1 bedroom flat",
    "propertyUrl": "https://www.rightmove.co.uk/property-to-rent/property-1.html",
    "students": False,
    "summary": "<h3>Full description</h3>",
    "transactionType": "rent",
}

initialized = {
    "banned": False,
    "bedrooms": 1,
    "displayAddress": "Fairlight Road, Tooting, SW17",
    "favorite": False,
    "featuredProperty": False,
    "feesApply": True,
    "feesApplyText": "",
    "firstVisibleDate": datetime.datetime(2019, 4, 26, 19, 9, 54),
    "floorplanImages": ("https://media.rightmove.co.uk/dir/112k/600x600.png",),
    "id": "RM-81242870",
    "keyFeatures": ("Superb one bedroom flat",),
    "lettingInformation": {"Furnishing": "Unfurnished"},
    "location": {"latitude": 52.0, "longitude": -1.0},
    "price": {"amount": 1300, "currencyCode": "GBP", "frequency": "monthly"},
    "propertyImages": ("https://media.rightmove.co.uk/dir/112k/656x437.jpg",),
    "propertySubType": "Flat",
    "propertyTypeFullDescription": "1 bedroom flat",
    "propertyUrl": "https://www.rightmove.co.uk/property-to-rent/property-1.html",
    "students": False,
    "summary": "<h3>Full description</h3>",
    "toWork": None,
    "transactionType": "rent",
}
