import datetime

data = {
    "banned": False,
    "bedrooms": 1,
    "displayAddress": "Fairlight Road, Tooting, SW17",
    "favorite": False,
    "featuredProperty": True,
    "feesApply": True,
    "feesApplyText": "foo",
    "firstVisibleDate": datetime.datetime(2019, 4, 26, 19, 9, 54),
    "floorplanImages": ("https://media.rightmove.co.uk/dir/112k/600x600.png",),
    "id": "RM-81242870",
    "keyFeatures": ("Superb one bedroom flat",),
    "lettingInformation": {"Furnishing": "Unfurnished"},
    "location": {"latitude": 52.0, "longitude": -1.0},
    "price": {"amount": 1300, "currencyCode": "GBP", "frequency": "monthly"},
    "propertyImages": ("https://media.rightmove.co.uk/dir/112k/656x437.jpg",),
    "propertySubType": "Flat",
    "propertyTypeFullDescription": "1 bedroom flat",
    "propertyUrl": "https://www.rightmove.co.uk/property-to-rent/property-1.html",
    "students": False,
    "summary": "<h3>Full description</h3>",
    "toWork": {
        "arrival_time": None,
        "departure_time": None,
        "distance": {"text": "12.9 km", "value": "12861"},
        "duration": {"text": "41 mins", "value": "2473"},
        "end_address": "102 Wardour St, Soho, London W1F 0TP, UK",
        "end_location": {"lat": 52, "lng": -0.1},
        "overview_polyline": {"points": "ey{x"},
        "start_address": "46 Fairlight Rd, Tooting, London SW17 0JD, UK",
        "start_location": {"lat": 51.4294749, "lng": -0.1761259},
        "steps": (),
        "traffic_speed_entry": (),
        "via_waypoint": (),
    },
    "transactionType": "rent",
}
